parameters:
    twilio.sid: '%env(TWILIO_ACCOUNT_SID)%'
    twilio.token: '%env(TWILIO_AUTH_TOKEN)%'
    twilio.verification_sid: '%env(TWILIO_VERIFICATION_SID)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Security\OTPService:
        class: App\Security\OTPService
        arguments:
            $twilioSID: '%twilio.sid%'
            $twilioToken: '%twilio.token%'
            $twilioVerificationSID: '%twilio.verification_sid%'
